### ISSUE TITLE
What will be done when import a privateKey

### ISSUE THREAD

**Issue by mivanzhang** [blockchain/My-Wallet-V3-Android#1244]
https://github.com/blockchain/My-Wallet-V3-Android/blob/develop/wallet/src/main/java/info/blockchain/wallet/payload/data/HDWallet.java
has method  ```getDeterminedSize```

the code here ,look ahead  for ten times? why  this can terminate searching all address?

**Comment by ditn** [comment]
It's not possible to search all addresses, so we look ahead ten addresses from the last one with a balance and stop once we've found a "gap" of ten. If you have more than ten addresses which are unused with the 11th used, your client likely has some kind of issue.

**Comment by mivanzhang** [comment]
so the above solution may got into troubles in some situation. Thanks for your reply, best regard
