### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by huanleyuan** [blockchain/My-Wallet-V3-Android#1250]
Execution failed for task ':app:processEnvDevDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  E:\workspace\My-Wallet-V3-Android\app\src\env\dev\debug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\envDev\debug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\debug\envDev\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\env\debug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\env\dev\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\env\devDebug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\envDev\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\debug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\envDevDebug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\env\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\src\envDebug\google-services.json
  E:\workspace\My-Wallet-V3-Android\app\google-services.json

**Comment by cindyvbautista** [comment]
did anyaone solve this issue? Thanks

**Comment by arindam9851** [comment]
Please solve this issue.

**Comment by pzhangleo** [comment]
try to add your own json file.

**Comment by Giszmo** [comment]
I'd like to bump this issue as it also impeded us in our attempt to verify the wallet for https://walletscrutiny.com/posts/2019/11/blockchainwallet/

**Comment by dserrano-bc** [comment]
this has now been fixed, please see the updated readme for quick start instructions
