### ISSUE TITLE
Make the build verifiable

### ISSUE THREAD

**Issue by Giszmo** [blockchain/My-Wallet-V3-Android#1256]
A wallet application is something very sensitive. A careless maintainer catching a backdoor might be enough to have an APK infected if internally build verification is not routinely exercised. Of course the public scrutiny is the other reason you want your app to be verifiable.

I tried to reproduce the current build but failed. My findings are in [this review](https://walletscrutiny.com/posts/2019/11/blockchainwallet/).

Fixing #1250 would probably help a lot.

With 5 million users I hope you see the urgency in making the app verifiable.

**Comment by Giszmo** [comment]
3 months later and no reply ... Is this the correct repository for [this wallet](https://play.google.com/store/apps/details?id=piuk.blockchain.android)?

**Comment by WasanTantiwararom** [comment]
ฉันไม่แน่ใจว่ากระเป๋าเงินของฉันมันมีอยู่จริงหรือไม่?
เพราะฉันยังไม่เคยเห็นและรับรู้ว่าในนั้นมีทรัพย์สินหรือว่างเปล่า?
ฉันตามมันเหมือนได้เจอ แต่ทำอะไรกับมันไม่ได้เหมือนสุภาษิตไทยที่กล่าวไว้
คนที่ทำ ไม่มีสิทธิได้ใช้
คนที่ได้ใช้  ไม่ได้ทำมัน
ขอบคุณที่ยังกลับมาดูความเป็นไปของฉัน
หากคุณมีคำแนะนำหรือวิธีปลดล็อคมันโปรดช่วยฉัน

**Comment by dserrano-bc** [comment]
Hi @Giszmo , please check the updated quick start section in the readme, we've made it as easy as possible to start up a working build!

**Comment by Giszmo** [comment]
@dserrano-bc thank you for your update. Apparently the latest version is in staged rollout as I don't see it on my phone yet. I did try to build it though and was more successful this time although it would have been helpful if the build instructions were also available for console builds. Took me a while to figure out this works:

```
./gradlew :app:assembleEnvProdRelease -x :app:lintVitalEnvProdRelease
```

WalletScrutiny.com was updated accordingly and I expect to be able to compare my build with the playstore release shortly.

**Comment by dserrano-bc** [comment]
@Giszmo it is indeed in staged rollout, you'll get the updated version hopefully very soon! Thanks for the command line build details, i will see if we can update the readme with these in the future.

**Comment by Giszmo** [comment]
So I now got hands on the latest update and cannot reproduce it with the source code provided. Please consider my [updated review](https://walletscrutiny.com/posts/2019/11/blockchainwallet/).

**Comment by Giszmo** [comment]
Seriously? No interest at all?
