### ISSUE TITLE
Missing code for latest release 8.8.4 on google-play

### ISSUE THREAD

**Issue by emanuelb** [blockchain/My-Wallet-V3-Android#1293]
While the google-play version is 8.8.4 Updated: June 25, 2021
https://play.google.com/store/apps/details?id=piuk.blockchain.android
As can be seen when downloading the app / using aurora store: https://auroraoss.com/download/
or via websites such as appbrain/apkpure:
https://www.appbrain.com/app/blockchain-com-wallet-buy-bitcoin-eth-crypto/piuk.blockchain.android
https://apkpure.com/blockchain-com-wallet-buy-bitcoin-eth-crypto/piuk.blockchain.android

Latest tag is for previous version v8.8.2 https://github.com/blockchain/My-Wallet-V3-Android/releases/tag/v8.8.2(647)
Latest commit is still version 8.8.2:
https://github.com/blockchain/My-Wallet-V3-Android/blob/5c162bcecfc70942a975e1b55ff71231008a1506/buildSrc/src/main/java/Dependencies.kt#L11

Please ensure the source-code is published in this repo before related version is uploaded to google-play!!!
This **VERY BAD** behavior already happen many times in this blockchain app, see previous issues for such missing sources cases:
#1291 #1270  #1255 https://github.com/blockchain/My-Wallet-V3-iOS/issues/640

**Comment by emanuelb** [comment]
In commit: https://github.com/blockchain/My-Wallet-V3-Android/commit/4b1343956ae4079fac95b7242d124b710db361de#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0

The versionName name changed from 8.8.2 to 8.8.5, also tag for 8.8.5 version was published: https://github.com/blockchain/My-Wallet-V3-Android/releases/tag/v8.8.5(654)

But what about the 8.8.4 version still on google-play which has VersionCode 651?

**Comment by Giszmo** [comment]
Version 8.8.7 is not available on GitHub neither.

**Comment by emanuelb** [comment]
This issue about version 8.8.4 that's missing in code, opened general issue regarding the broken process that result in publishing code later after related version is available in Google Play in #1294 so in future comments for missing source-code is better to open issue for them or comment on the linked issue.

**Comment by mistychatmsn** [comment]
Code 647
Misty chatman 1010 outer rd 215 san diago ca 92154
1(619)-541-9282

**Comment by Apache-wep** [comment]
I would like have meeting with you thank you

**Comment by emanuelb** [comment]
Closing issue in favor of #1294 which will be updated when version released on google-play before sources for it are published, currently sources for latest release "202203.1.1" are published with matching tag/release https://github.com/blockchain/My-Wallet-V3-Android/releases/tag/v202203.1.1(19196)

**Comment by mistychatmsn** [comment]
Yes sir hello may I you you can reach me at 619-541-9282
My name is Misty Chatman
When is the best time to have a meeting please feel free to call me
