### ISSUE TITLE
[BIP39] Integrate foreign wordlists

### ISSUE THREAD

**Issue by Kirvx** [blockchain/My-Wallet-V3-Android#209]
Is it planned to use the foreign wordlists of BIP39 ?:
https://github.com/bitcoin/bips/tree/master/bip-0039

Chinese - French - Italian - Japanese - Spanish

Given that the app is available in multi languages I think it's a logical move.

**Comment by pernas** [comment]
Even I am not a native english speaker I think that using other dictionaries make your mnemonic a little bit less standard because there are lots of software that does not support other dictionaries. Hence, I don't think it is a logical move. But that is my personal opinion.

**Comment by Kirvx** [comment]
Breadwallet and Copay use these other dictionnaries.

The recovery phrase could be proposed in english by default, but with the option to choose an other language.
