### ISSUE TITLE
Opening the wallet from recent apps does not require PIN 

### ISSUE THREAD

**Issue by Empty2k12** [blockchain/My-Wallet-V3-Android#263]
I don't know if this is intended behavior or a bug but when opening the Blockchain.info Wallet (v 6.1.26) from the recent apps menu the pin code is not required. 
When first opening the app the pin is still asked for. 

I made a video documenting the bug: https://youtu.be/w0Nca2lsuPw

I am using the Nextbit Robin with its stock ROM (Android 6.0.1)

I will be happy to provide more info on request.

**Comment by riaanjvos** [comment]
@Empty2k12 thanks for letting us know about this. I'll get back to you as soon as we start investigating it.

**Comment by Empty2k12** [comment]
What's the status on this? Non reproducible, fixed, wontfix?

**Comment by ditn** [comment]
Apologies for not explaining - the PIN/auth flow has been completely rearchitected since this report, and as such we haven't been able to reproduce the bug you reported.
