### ISSUE TITLE
Mobile only

### ISSUE THREAD

**Issue by DarkLordGMS** [blockchain/My-Wallet-V3-Android#694]
Have you considered adding an option to make a mobile wallet only?

I mean, when you install the app for the first time, instead of asking the user to register using an e-mail and password, why don't you add an option where the user can just skip the registration and make it so that the wallet is only stored locally in the mobile device. 

Users who choose this option would have to save their recovery seed in a safe place to be able to recover their wallets in the future. In my opinion this would be more safe because an online wallet can be hacked easily if the password is weak but to hijack a mobile wallet you would need physical access to the mobile device + the owners pin or fingerprint.

**Comment by ditn** [comment]
Hey there,

This is actually something that the Android team have discussed at length; it's an interesting idea, but it would require quite a lot of work on our end. For now this isn't likely to happen, but we may look into it more seriously in the medium-long term.

Thanks for the great suggestion!
