### ISSUE TITLE
secret.properties does not exist ? 

### ISSUE THREAD

**Issue by sharity-app** [blockchain/My-Wallet-V3-Android#714]
secret.properties does not exist when compiling with gradle i get a "secret.properties does not exist" error.. something missing ?

**Comment by ditn** [comment]
Yes, we use Novoda's [build properties plugin](https://github.com/novoda/gradle-build-properties-plugin) to keep secret information, such as URLs, API keys and other info out of the public domain.

To get the app to compile, you'll need to add your own `secrets.properties` file with the information defined with the names you see in the app-level `build.gradle`. This includes registering for a Google Maps V2 key and for Firebase, and you'll need to add a valid `google-services.json` file in the app root. You'll also need to comment out/remove the `afterEvaluate` block in `build.gradle`, which checks for the hash of our specific `google-services.json` configuration.

**Comment by sharity-app** [comment]
I got that part. But what does "EXPLORER_URL","API_URL", "WEBSOCKET_URL,
Are supposed to stand for ?

**Comment by ditn** [comment]
All of the endpoints are documented [here](https://blockchain.info/api). For simplicity's sake, see below for an example production-only `secrets.properties` file:

```
# Explorer URL
prodExplorer=https://blockchain.info/

# API URL
prodApiServer=https://api.blockchain.info/

# Bitcoin Websocket URL
prodWebsocketServer =wss://ws.blockchain.info/inv
```

**Comment by mehhrad** [comment]
would you give us an working sample config ?
