### ISSUE TITLE
Can't login to app

### ISSUE THREAD

**Issue by pashakiz** [blockchain/My-Wallet-V3-Android#798]
After scaning the QR Code from website on PC I getting the popup window with this text:

> Мы требуем ввода второго пароля, чтобы пользоваться этой услугой. Чтобы настроить свой Ether кошелек, вам нужно будет ввести это только один раз

What the second password? I tryed.. This popup don't passing me..

**Comment by ditn** [comment]
You have set a second password on your wallet - the one you enter when confirming a transaction. We need it once only when setting up Ethereum support on your device.

**Comment by pashakiz** [comment]
I understand, but I tryed various passwords - and still can't login...
I'm entering password, then touching "OK" and this window refreshing and I see error text:
"Недействительный пароль"
Sorry, that I didn't describe this in first message.

**Comment by ditn** [comment]
I see, in that case you'll need to restore your wallet to a new account from the 12 word recovery phrase. Do you have your wallet backed up?

**Comment by pashakiz** [comment]
Yes. What exactly should I do?
Go to the blockchain.info/wallet/recover ?

**Comment by ditn** [comment]
That's great. Either create a new wallet [here](https://blockchain.info/wallet/#/recover), or uninstall and reinstall the app on your device and select `Recover Funds` on the landing page. It's fine to use the same email address, but please make a note of your new GUID. 

Let us know how it goes.

**Comment by pashakiz** [comment]
I recovered wallet and now can login to mobile App. Thank you for help!
