### ISSUE TITLE
Root warning disable

### ISSUE THREAD

**Issue by jamesweech** [blockchain/My-Wallet-V3-Android#81]
Hi,

It is a bit annoying every time I open the Blockchain app I get a warning about my device being rooted and the security implications, I understand it can make your device a lot more vulnerable and I am ok with that due to all the apps which have root access on my handset have been code audited.

Is there any way to have a "don't show again" option in preference? It's small I know but a bit of a pain none the less.

Thank you for such an amazing app

**Comment by mpfluger** [comment]
Thanks for your feedback. We'll fix that in an upcoming build.

**Comment by jamesweech** [comment]
Thank you :+1:

**Comment by mpfluger** [comment]
Fixed in the code and will be included in the next build. There is now a setting to disable this warning.
