### ISSUE TITLE
Is it possible to create a new account without a password?

### ISSUE THREAD

**Issue by crypto-recovery** [blockchain/My-Wallet-V3-Android#846]
My name is Chris, and I run a service to help folks that hold cryptoassets recover lost passwords.

I have a client whose Andriod phone was stolen, and who doesn't have the 12 word recovery key.

She still controls the email address associated with the wallet and was able to retrieve her Wallet ID. Through her Wallet ID I was able to download a backup of her wallet (the wallet.aes.json file).  In general, if the account holder has a good idea of their password that's enough information to brute force recover the password.

However, my client is adamant that she never created a password when she created the Blockchain.info account on her phone.  She claims to have only created a 4-character pin or used her thumbprint to access the account.

(In my testing I always have to create a 9-character+ password).

Is it possible that my client is right? Is it possible to create a Blockchain.info account on an Android phone without a password?  If so, do you create a default password (perhaps based on the pin?) for those accounts.

Thank you -- I really appreciate your help.

**Comment by ditn** [comment]
Hi Chris,

Yes it is possible that your client created a wallet with only a PIN code. Very early versions of the wallet only used the PIN to generate the password by concatenating the PIN 3 times, [as you can see here](https://github.com/blockchain/My-Wallet-V2-Android/blob/master/src/info/blockchain/wallet/ui/PinCreateActivity.java#L381). This should make it fairly trivial for you to recover the key.

Let us know if this works for you.

**Comment by crypto-recovery** [comment]
Hi Adam,

Sure, it's: cryptoassetrecovery@gmail.com

Thanks,
Chris

**Comment by LewisBaker** [comment]
Yes it is very possible to recover funds in wallet without your 12-word recovery steps.
Visit www.primefinancerecovery.com and contact to report cases of lost global funds of cryptocurrency, online trading, forex, binary trading/options, and assets to fraudulent brokers, individual agents, or companies. They also offer to assist in crypto-trading investments and serve as better financial advisories.
