### ISSUE TITLE
Can't run project ?

### ISSUE THREAD

**Issue by chihung93** [blockchain/My-Wallet-V3-Android#901]
Hello you guys,
I think the problem is due to no app / secrets.properties file, so 
Where should I find the app / secrets.properties file?
TKs.

```
Error:Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hungdct/Downloads/My-Wallet-V3-Android-master/app/build.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':app'.
> File secrets.properties does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by ditn** [comment]
Hi, see #714.

Apologies for this, we'll add some documentation and a bare-bones `secrets.properties` file in the next week or so.

**Comment by BalachandarMarimuthu** [comment]
Hi Guys,

app / secrets.properties issue is not yet fixed. Kindly update and fix this.

**Comment by abewangm** [comment]
secrets.properties issue was still not got fixed.

**Comment by Game-TA** [comment]
meet the same issue

**Comment by AmyWuGo** [comment]
meet the same issue

**Comment by mynameyi** [comment]
I need a bare-bones secrets.properties file

**Comment by ditn** [comment]
Hey all, apologies for this. We've added a default configuration in https://github.com/blockchain/My-Wallet-V3-Android/pull/1067 on `develop`, which should get you most of the way there. 

You'll still need to provide a Google Services JSON file to run the project; we may come up with a solution for that in the future but for now you'll need to remove the `google-services` plugin from `app/build.gradle` and disable Firebase in `BlockchainApplication`.
